#!/bin/sh

cd `dirname "$0"`
navicat_root=`pwd`

# Wine environment variables
WINEDIR="wine"
export LANG="en_US.UTF-8"
export PATH="$navicat_root/$WINEDIR/bin":"$navicat_root":"$navicat_root/$WINEDIR/drive_c/windows":"$PATH"
export LD_LIBRARY_PATH="$navicat_root/$WINEDIR/lib":"$navicat_root/lib":"$LD_LIBRARY_PATH"
export WINEDLLPATH="$navicat_root/$WINEDIR/lib/wine"
export WINELOADER="$navicat_root/$WINEDIR/bin/wine64"
export WINESERVER="$navicat_root/$WINEDIR/bin/wineserver"
export WINEPREFIX="$HOME/.navicat64"
export WINEDLLOVERRIDES="ucrtbase,msvcp140,vcruntime140,msvcp110,msvcr110,msxml3=n,b"

# wine version
if [ -f "$WINEPREFIX/Version" ] ; then
  echo "110200" > "$WINEPREFIX/Version"
fi

# create directories
[ -d "$WINEPREFIX" ] || mkdir -p "$WINEPREFIX"
[ -d "$WINEPREFIX/drive_c" ] || mkdir -p "$WINEPREFIX/drive_c"
[ -d "$WINEPREFIX/drive_c/Program Files" ] || mkdir -p "$WINEPREFIX/drive_c/Program Files"
[ -d "$WINEPREFIX/drive_c/windows" ] || mkdir -p "$WINEPREFIX/drive_c/windows"
[ -d "$WINEPREFIX/drive_c/windows/temp" ] || mkdir -p "$WINEPREFIX/drive_c/windows/temp"
[ -d "$WINEPREFIX/drive_c/windows/system32" ] || mkdir -p "$WINEPREFIX/drive_c/windows/system32"
[ -d "$WINEPREFIX/dosdevices" ] || mkdir -p "$WINEPREFIX/dosdevices"

# create Navicat directories
[ -f "$WINEPREFIX/Navicat" ] && rm -f "$WINEPREFIX/Navicat"
[ -d "$WINEPREFIX/Navicat" ] || mkdir -p "$WINEPREFIX/Navicat"

# create wine emulated devices
if [ -h "$WINEPREFIX/dosdevices/c:" ] ; then
  [ -d "$WINEPREFIX/dosdevices/c:" ] || rm -f "$WINEPREFIX/dosdevices/c:"
fi
[ -d "$WINEPREFIX/dosdevices/c:" ] || ln -s "$WINEPREFIX/drive_c/" "$WINEPREFIX/dosdevices/c:"

if [ -h "$WINEPREFIX/dosdevices/z:" ] ; then
  [ -d "$WINEPREFIX/dosdevices/z:" ] || rm -f "$WINEPREFIX/dosdevices/z:"
fi
[ -d "$WINEPREFIX/dosdevices/z:" ] || ln -s / "$WINEPREFIX/dosdevices/z:"

if [ -h "$WINEPREFIX/dosdevices/y:" ] ; then
  [ -d "$WINEPREFIX/dosdevices/y:" ] || rm -f "$WINEPREFIX/dosdevices/y:"
fi
if [ -d "$HOME" ] ; then
    [ -d "$WINEPREFIX/dosdevices/y:" ] || ln -s "$HOME" "$WINEPREFIX/dosdevices/y:"
fi

# create symlinks to dlls in WINEDLLOVERRIDES
for dll_name in \
  ucrtbase.dll \
  msvcp140.dll \
  vcruntime140.dll \
  msxml3.dll \
  msxml3r.dll \
  fontsub.dll \
  msvcp110.dll \
  msvcr110.dll \
  ; do
  if [ ! -h "$WINEPREFIX/drive_c/windows/system32/$dll_name" ] || [ `readlink "$WINEPREFIX/drive_c/windows/system32/$dll_name"` != "$navicat_root/$WINEDIR/drive_c/windows/system32/$dll_name" ] ; then
    rm -rf "$WINEPREFIX/drive_c/windows/system32/$dll_name"
    ln -s "$navicat_root/$WINEDIR/drive_c/windows/system32/$dll_name" "$WINEPREFIX/drive_c/windows/system32/$dll_name"
  fi
done

# hide error/stdout message
if test "z$WINEDEBUG" = z ; then
  exec >/dev/null 2>&1
fi

# create wine environment, for ShowDotFiles
[ -f "$WINEPREFIX/system.reg" ] || `WINEDLLOVERRIDES="mshtml=" $navicat_root/$WINEDIR/bin/wineboot -i`

# run Navicat.exe
exec "${WINELOADER:-wine}" "$navicat_root/Navicat/Navicat.exe" "$1" "$2" "$3" "$4" "$5" "$6" "$7"
